config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 

  get 'angular-items', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :portfolios do
    member do
      patch :sort
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/blog.rb
class Blog < ApplicationRecord
  enum status: { draft: 0, published: 1 }
  extend FriendlyId
  friendly_id :title, use: :slugged

  validates_presence_of :title, :body, :topic_id

  belongs_to :topic

  has_many :comments, dependent: :destroy

  def self.special_blogs
    all
  end

  def self.featured_blogs
    limit(2)
  end

  def self.recent
    order("created_at DESC")
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: %i[ show edit update destroy toggle_status ]
  before_action :set_sidebar_topics, except: [:update, :create, :destroy, :toggle_status]
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :toggle_status]}, site_admin: :all

  # GET /blogs or /blogs.json
  def index
    if logged_in?(:site_admin)
      @blogs = Blog.recent.page(params[:page]).per(5)
    else
      @blogs = Blog.published.recent.page(params[:page]).per(5)
    end
    @page_title = "Portfolio Blog"
  end

  # GET /blogs/1 or /blogs/1.json
  def show
    if logged_in?(:site_admin) || @blog.published?
      @blog = Blog.includes(:comments).friendly.find(params[:id])
      @comment = Comment.new

      @page_title = @blog.title
      @seo_keywords = @blog.body
    else
      redirect_to blogs_path, notice: "You are not authorized to access this page"
    end
  end

  # GET /blogs/new
  def new
    @blog = Blog.new
  end

  # GET /blogs/1/edit
  def edit
  end

  # POST /blogs or /blogs.json
  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to blog_url(@blog), notice: "Blog Post is now live." }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /blogs/1 or /blogs/1.json
  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to blog_url(@blog), notice: "Blog Post was successfully updated." }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /blogs/1 or /blogs/1.json
  def destroy
    @blog.destroy

    respond_to do |format|
      format.html { redirect_to blogs_url, notice: "Blog Post was successfully removed." }
      format.json { head :no_content }
    end
  end

  def toggle_status
    if @blog.draft?
      @blog.published!
    elsif @blog.published?
      @blog.draft!
    end

    redirect_to blogs_url, notice: "Post status has been updated."
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_blog
    @blog = Blog.friendly.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def blog_params
    params.require(:blog).permit(:title, :body, :topic_id, :status)
  end
  
  def set_sidebar_topics
    @side_bar_topics = Topic.with_blogs
  end
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def gravatar_helper user
    image_tag "https://www.gravatar.com/avatar/#{Digest::MD5.hexdigest(user.email)}", width: 60
  end

  class CodeRayify < Redcarpet::Render::HTML
    def block_code(code, language)
      CodeRay.scan(code, language).div
    end
  end

  def markdown(text)
    coderayified = CodeRayify.new(filter_html: true, hard_wrap: true)

    options = {
      fenced_code_blocks: true,
      no_intra_emphasis: true,
      autolink: true,
      lax_html_blocks: true,
    }

    markdown_to_html = Redcarpet::Markdown.new(coderayified, options)
    markdown_to_html.render(text).html_safe
  end

  def blog_status_color blog
    'color: red;' if blog.draft?
  end
end

app/views/blogs/_admin_actions.html.erb
<% if logged_in?(:site_admin) %>
  <nav class="breadcrumb blogcrumb d-flex justify-content-start gap-1">
    <%= link_to toggle_status_blog_path(blog), style: blog_status_color(blog), class: "btn btn-sm btn-secondary bg-white" do %>
      <%= fa_icon('file-text') %>
    <% end %>

    <%= link_to edit_blog_path(blog), class: "btn btn-sm btn-secondary bg-white" do %>
      <%= fa_icon('pencil-square-o') %>
    <% end %>

    <%= button_to blog_path(blog),
      method: :delete,
      data: { turbo_confirm: 'Are you sure?' },
      form: { class: "d-flex justify-content-center btn btn-sm btn-secondary bg-white" },
      class: "bg-white border-0" do %>
        <%= fa_icon('trash', class: 'icon-large') %>
    <% end %>

  </nav>
<% end %>

app/views/blogs/_blog.html.erb
<div class="card text-start text-lg-center px-2 px-lg-4">
  <h2 class="mt-2">
    <%= link_to blog.title.upcase, blog, class: "text-light-black" %>
  </h2>

  <p class="published-text">Published <%= distance_of_time_in_words(blog.created_at, Time.now) %> ago</p>

  <%= render partial: 'blogs/admin_actions', locals: { blog: blog } %>

  <p class="text-start">
    <%= blog.body %>
  </p>
</div>

app/views/blogs/_form.html.erb
<%= form_for(blog, html: { data: { turbo: false } }) do |f| %>

  <%= render "shared/form_errors", object: blog %>

  <div class="form-group">
    <%= f.label :title, class: "mb-1" %>
    <%= f.text_field :title, class: 'form-control', placeholder: "Title" %>
  </div>

  <div class="form-group">
    <%= f.label :topic_id, class: "mb-1" %>
    <%= f.collection_select(:topic_id, Topic.all, :id, :title,
                              {
                                selected: blog.topic&.id,
                                include_blank: true
                              },
                              class: 'form-control'
                            )
    %>
  </div>

  <div class="form-group">
    <%= f.radio_button :status, 'draft' %>
    <%= f.label :status, 'Draft', class: "mb-1" %>

    <%= f.radio_button :status, 'published' %>
    <%= f.label :status, 'Published', class: "mb-1" %>
  </div>

  <div class="form-group">
    <%= f.text_area :body, class: 'form-control', rows: 15, placeholder: "Content" %>
  </div>

  <div class="form-group d-flex gap-2">
    <%= f.submit "Submit", class: 'btn btn-primary' %>
    <%= link_to 'Back', blogs_path, class: 'btn btn-primary bg-white text-black' %>
  </div>

<% end %>

app/views/blogs/edit.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">Editing Blog</h1>
  <hr>
</div>

<div class="blog-container bg-tranparent">

  <div class="row">
    
    <div class="col-md-8">
      <div class="d-flex flex-column gap-3">
        <%= render 'form', blog: @blog %>
      </div>

    </div>

    <div class="col-md-4">
      <div class="<%= logged_in?(:site_admin) ? '' : 'mt-3 mt-md-0' %>">
        <%= render "shared/blog_sidebar" %>
      </div>
    </div>

  </div>
</div>

app/views/blogs/index.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">My Blog</h1>
  <hr>
</div>

<div class="blog-container bg-tranparent">
  <%= render "shared/blog_masthead" %>

  <div class="row mt-3">
    
    <div class="col-md-8">
      <div class="d-flex flex-column gap-3">
        <%= render @blogs %>
      </div>

      <%= paginate @blogs %>
    </div>

    <div class="col-md-4">
      <div class="<%= logged_in?(:site_admin) ? '' : 'mt-3 mt-md-0' %>">
        <%= render "shared/blog_sidebar" %>
      </div>
    </div>

  </div>
</div>

app/views/blogs/new.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">New Blog</h1>
  <hr>
</div>

<div class="blog-container bg-tranparent">

  <div class="row">
    
    <div class="col-md-8">
      <div class="d-flex flex-column gap-3">
        <%= render 'form', blog: @blog %>
      </div>

    </div>

    <div class="col-md-4">
      <div class="<%= logged_in?(:site_admin) ? '' : 'mt-3 mt-md-0' %>">
        <%= render "shared/blog_sidebar" %>
      </div>
    </div>

  </div>
</div>

app/views/blogs/show.html.erb
<div>
  <h1 class="mt-4 mt-lg-5"><%= @blog.title %></h1>
  <hr>
</div>

<div class="blog-container bg-tranparent">
  <div class="row">

    <div class="col-sm-8">
      <nav class="breadcrumb">
        <%= link_to "Home", root_path, class: 'breadcrumb-item' %>
        <%= link_to @blog.topic.title, topic_path(@blog.topic), class: 'breadcrumb-item' %>

        <span class="breadcrumb-item active text-white"><%= @blog.title %></span>
      </nav>

      <% if logged_in?(:site_admin) %>
        <div class="d-flex justify-content-start mb-3">
          <%= link_to 'Edit', edit_blog_path(@blog), class: 'btn btn-sm btn-secondary bg-white' if logged_in?(:site_admin) %>
        </div>
      <% end %>

      <div class="card text-start px-2 px-lg-3 mb-3">
        <p>
          <%= markdown @blog.body %>
        </p>

        <% if logged_in?(:site_admin) %>
          <h2>Comments</h2>
        <% end %>

        <%= render 'comments/comment_form' %>

        <div id="comments" class="mb-2" data-blog-id="<%= @blog.id %>">
          <%= render @blog.comments %>
        </div>

        <%= turbo_stream_from "blog_#{@blog.id}_comments" %>
      </div>
      
    </div>

    <div class="col-md-4">
      <%= render "shared/blog_sidebar" %>
    </div>
    
  </div>
</div>