config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 

  get 'angular-items', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :portfolios do
    member do
      patch :sort
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  acts_as_list
  
	has_many :technologies
	accepts_nested_attributes_for :technologies,
                                allow_destroy: true,
								                reject_if: lambda { |attrs| attrs['name'].blank? }

  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.angular
    where(subtitle: "Angular")
  end

  scope :ruby_on_rails_portfolio_items, -> { where(subtitle: "Ruby on Rails") }

end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio_item, only: [:edit, :show, :update, :destroy]
  access all: [:show, :index, :angular], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
  def index
    @portfolio_items = Portfolio.order(:position)
  end  
  
  def sort
    @portfolio_item = Portfolio.find(params[:id])
    @portfolio_item.insert_at(params[:position].to_i + 1)
    head :ok
  end

  def angular
    @angular_portfolio_items = Portfolio.angular
  end

  def new
    @portfolio_item = Portfolio.new
  end

  def create
    @portfolio_item = Portfolio.new(portfolio_params)
  
    respond_to do |format|
      if @portfolio_item.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio Item is now live.' }
        format.turbo_stream { render turbo_stream: turbo_stream.replace('portfolio_form', partial: 'form', locals: { portfolio_item: @portfolio_item }) }
      else
        format.html { render :new }
        format.turbo_stream { render turbo_stream: turbo_stream.replace('portfolio_form', partial: 'form', locals: { portfolio_item: @portfolio_item }) }
      end
    end
  end

  def edit
  end

  def show
  end

  def update
    respond_to do |format|
      if @portfolio_item.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'The portfolio item was successfully updated.' }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('portfolio_form', partial: 'form', locals: { portfolio_item: @portfolio_item })
        end
      else
        format.html { render :edit }
        format.turbo_stream do
          render turbo_stream: turbo_stream.replace('portfolio_form', partial: 'form', locals: { portfolio_item: @portfolio_item })
        end
      end
    end
  end  

  def destroy
    #destroy/delete the record
    @portfolio_item.destroy

    #redirect
    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Portfolio was sucessfully removed.' }
    end
  end

  private

  def portfolio_params
    params.require(:portfolio).permit(:title,
                                      :subtitle,
                                      :body,
                                      :main_image,
                                      :thumb_image,
                                      technologies_attributes: [:id, :name, :_destroy]
                                     )
  end

  def set_portfolio_item
    @portfolio_item = Portfolio.find(params[:id])
  end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def portfolio_img(img, type)
    if img.present? && img.url.present?
      img.url
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
  
end

app/views/portfolios/_form.html.erb
<div id="portfolio_form">
  <%= form_for @portfolio_item, html: { data: { turbo: false } } do |f| %>

    <%= render 'shared/form_errors', object: @portfolio_item %>

    <div class="row">
      <div class="col-md-8">
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :subtitle %>
          <%= f.text_field :subtitle, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :main_image, 'Main Image', class: 'form-label' %>
          <%= f.file_field :main_image, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :thumb_image, 'Thumbnail Image', class: 'form-label' %>
          <%= f.file_field :thumb_image, class: 'form-control' %>
        </div>

        <div class="form-group">
          <%= f.label :body %>
          <%= f.text_area :body, class: 'form-control', rows: 13 %>
        </div>
      </div>
    </div>

    <hr>

    <div class="col-md-8">
      <h2 class="text-start">Technologies Used:</h2>
      <div>
        <%= f.fields_for :technologies do |technology_form| %>
          <%= render 'technology_fields', f: technology_form %>
        <% end %>

        <div>
          <%= link_to_add_association 'Add Technology', f, :technologies, data: { turbo: false }, class: 'btn btn-primary btn-block w-100 mt-2' %>
        </div>
      </div>

      <div class="form-group mt-5">
        <%= f.submit 'Save Portfolio Item', class: 'btn btn-secondary text-white' %>
      </div>
    </div>
  <% end %>
</div>

app/views/portfolios/_portfolio_item.html.erb
<%= link_to portfolio_path(portfolio_item) do %>
  <div class="card shadow-sm">

    <% if portfolio_item.thumb_image.present? %>
      <%= image_tag portfolio_img(portfolio_item.thumb_image, 'thumb'),
          class: 'card-img-top img-fluid object-fit-cover',
          style: 'height: 225px; object-fit: cover;' %>
    <% else %>
      <svg class="bd-placeholder-img card-img-top" width="100%" height="225" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: sample_image" preserveAspectRatio="xMidYMid slice" focusable="false">
        <title>Placeholder</title>
        <rect width="100%" height="100%" fill="#55595c"/>
        <text x="50%" y="50%" fill="#eceeef" dy=".3em" text-anchor="middle">Image</text>
      </svg>
    <% end %>

    <div class="card-body flex-grow-1">
      <p class="card-text">
        <span class="text-light-black fw-bold">
          <%= portfolio_item.title %>
        </span>

        : <%= portfolio_item.subtitle %>
      </p>
    </div>

  </div>
<% end %>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/angular.html.erb
<h1> Portfolio Items </h1>

<%= link_to "Create New Item", new_portfolio_url if logged_in?(:site_admin) %>

<% @angular_portfolio_items.each do |portfolio_item| %>
    <p><%= link_to portfolio_item.title, portfolio_path(portfolio_item) %></p>
    <p><%= portfolio_item.subtitle %></p>
    <p><%= portfolio_item.body %></p>
    <%= image_tag portfolio_item.thumb_image unless portfolio_item.thumb_image.nil? %>
    <%= link_to "Edit", edit_portfolio_path(portfolio_item) if logged_in?(:site_admin) %>
    <%= button_to portfolio_path(portfolio_item),
      method: :delete,
      data: { turbo_confirm: "Are you sure?" },
      form: { class: "d-inline" },
      class: "btn btn-sm btn-secondary bg-white d-flex justify-content-center align-items-center border-0" do %>
      <%= fa_icon('trash', class: 'icon-large') %>
    <% end if logged_in?(:site_admin) %>

<% end %>

app/views/portfolios/edit.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">Edit Portfolio Item</h1>
  <hr>
</div>

<div class="portfolio-container bg-tranparent">
  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">Portfolio Items</h1>
  <hr>
</div>

<div class="portfolio-container bg-tranparent">
  <%= source_helper("alert alert-warning") %>

  <%= tag.div class: "row gy-4", data: (logged_in?(:site_admin) ? { controller: "sortable" } : {}) do %>
    <% @portfolio_items.each do |portfolio_item| %>
      <div class="col-md-4">
        <div data-id="<%= portfolio_item.id %>">
          <%= render partial: 'portfolio_item', locals: { portfolio_item: portfolio_item } %>
        </div>
      </div>
    <% end %>
  <% end %>
</div>

app/views/portfolios/new.html.erb
<div>
  <h1 class="mt-4 mt-lg-5">Create a new Portfolio Item</h1>
  <hr>
</div>

<div class="portfolio-container bg-tranparent">
  <%= render 'form', portfolio_item: @portfolio_item %> 
</div>

app/views/portfolios/show.html.erb
<div>
  <h1 class="mt-4 mt-lg-5"><%= @portfolio_item.title %></h1>
  <hr>
</div>

<div class="portfolio-container bg-tranparent">
  <div class="row">
    <div class="col-md-7">
      <% if @portfolio_item.thumb_image.present? && @portfolio_item.thumb_image.url.present? %>
        <%= image_tag portfolio_img(@portfolio_item.main_image, 'main'), width: '100%' %>
      <% else %>
        <svg class="bd-placeholder-img card-img-top" width="300px" height="300px" xmlns="http://www.w3.org/2000/svg" role="img" aria-label="Placeholder: main_image" preserveAspectRatio="xMidYMid slice" focusable="false">
          <title>Placeholder</title>
          <rect width="100%" height="100%" fill="#55595c"/>
          <text x="50%" y="50%" fill="#eceeef" dy=".3em" text-anchor="middle">Main Image</text>
        </svg>
      <% end %>
    </div>

    <div class="col-md-5 text-start">
      <em><%= @portfolio_item.subtitle %></em>
      
      <p class="mt-3"><%= @portfolio_item.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% techs = @portfolio_item.technologies %>

      <% if techs.size > 6 %>
        <div class="row">
          <div class="col-md-6">
            <% techs.first((techs.size / 2.0).ceil).each do |tech| %>
              <span><%= tech.name %></span><br>
            <% end %>
          </div>
          <div class="col-md-6">
            <% techs.last((techs.size / 2.0).floor).each do |tech| %>
              <span><%= tech.name %></span><br>
            <% end %>
          </div>
        </div>
      <% else %>
        <% techs.each do |tech| %>
          <span><%= tech.name %></span><br>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="d-flex text-end mt-3">
    <%= link_to 'Back to Portfolios', portfolios_path, class: 'btn btn-primary bg-white text-black' %>
  </div>
</div>