config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' } 

  get 'angular-items', to: 'portfolios#angular'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'

  resources :portfolios do
    member do
      patch :sort
    end
  end
  
  resources :blogs do
    member do
      get :toggle_status
    end
  end
  
  mount ActionCable.server => '/cable'

  root to: 'pages#home'
end

app/views/shared/_alerts.html.erb
<div class="flash-container position-fixed top-0 end-0 p-3" style="z-index: 1055;" data-controller="flash">
  <% if flash[:alert] %>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <%= flash[:alert] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>

  <% if flash[:notice] %>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <%= flash[:notice] %>
      <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    </div>
  <% end %>
</div>

app/views/shared/_application_footer.html.erb
<div>
  <div class="inner">
    <p class="app-footer"><%= copyright_generator %></p>
  </div>
</div>

app/views/shared/_application_nav.html.erb
<div class="text-white w-100 sticky-top">
  <div class="navbar-bg w-100">
    <div class="inner container d-flex justify-content-between align-items-center">
      <h3 class="masthead-brand m-0 text-white">April Campos</h3>
      <nav class="nav nav-masthead app-nav">
        <%= nav_helper 'nav-link text-white', 'span' %>
        <%= login_helper 'nav-link text-white' %>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_blog_footer.html.erb
<footer class="blog-footer">
  <p>
    <%= copyright_generator %>
  </p>
  <p>
    <a href="#">Back to top</a>
  </p>
</footer>

app/views/shared/_blog_masthead.html.erb
<div class="d-flex justify-content-start gap-2">
  <%= link_to 'Write a New Blog', new_blog_path, class: 'btn btn-sm btn-secondary bg-white' if logged_in?(:site_admin)%>
  <%= link_to 'See All Topics', topics_path, class: 'btn btn-sm btn-secondary bg-white' %>
</div>

app/views/shared/_blog_nav.html.erb
<div class="blog-masthead">
  <div class="container">
    <nav class="nav blog-nav">
      <%= nav_helper 'nav-link', 'span' %>
      <%= login_helper 'nav-link' %>
    </nav>
  </div>
</div>

app/views/shared/_blog_sidebar.html.erb
<div class="blog-sidebar d-grid gap-3">
  
  <div class="card sidebar-card">
    <div class="card-body d-flex flex-column justify-content-center">
      <h4 class="card-title">About</h4>
      <p class="card-text">A space where I document my journey in web development, share tutorials, and explore new technologies.</p>
    </div>
  </div>
  
  <div class="card sidebar-card">
    <div class="card-body d-flex flex-column justify-content-center">
      <h4 class="card-title">Topics</h4>
      <% @side_bar_topics.each do |topic| %>
        <p><%= link_to topic.title, topic_path(topic), class: "text-light-black" %></p>
      <% end %>
    </div>
  </div>

  <div class="card sidebar-card">
    <div class="card-body d-flex flex-column justify-content-center">
      <h4 class="card-title">Elsewhere</h4>
      <div class="d-flex justify-content-center gap-3 p-0 m-0">
        <span>
          <a href="https://github.com/aprilcampos" target="_blank" class="social-icon">
            <%= fa_icon "github" %>
          </a>
        </span>
        <span>
          <a href="https://www.instagram.com/aprlcamlle" target="_blank" class="social-icon">
            <%= fa_icon "instagram" %>
          </a>
        </span>
        <span>
          <a href="https://www.facebook.com/aprilcamillecampos" target="_blank" class="social-icon">
            <%= fa_icon "facebook" %>
          </a>
        </span>
      </div>
    </div>
  </div>
</div>

app/views/shared/_form_errors.html.erb
<% if object.errors.any? %>
  <div class="alert alert-danger" role="alert">
    <h4 class="alert-heading">
      <%= pluralize(object.errors.count, "error") %> prohibited this <%= object.model_name.human.downcase %> from being saved:
    </h4>
    <ul class="mb-0">
      <% object.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_mobile_application_nav.html.erb
<div class="navbar-bg w-100">
  <div class="inner container d-flex flex-column">
    <div class="d-flex justify-content-between align-items-center w-100">
      <h3 class="masthead-brand m-0 text-white">April Campos</h3>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fa fa-bars"></i>
      </button>
    </div>

    <div class="collapse navbar-collapse" id="navbarNav">
      <nav class="nav flex-column align-items-start mt-3">
        <%= nav_helper 'nav-link text-white px-0 mx-0', 'span' %>
        <%= login_helper 'nav-link text-white px-0 mx-0' %>
      </nav>
    </div>
  </div>
</div>

app/views/shared/_nav.html.erb
<div class="<%= location %>">
  <div><%= link_to "Home", root_path %></div>
  <div><%= link_to "About Me", about_me_path %></div>
  <div><%= link_to "Contact", contact_path %></div>
  <div><%= link_to "Blog", blogs_path %></div>
  <div><%= link_to "Portfolio", portfolios_path %></div>
</div>

app/views/shared/_portfolio_footer.html.erb
<footer class="text-body-secondary py-5">
  <div class="container">
    <p class="float-end mb-1">
      <%= link_to "View All Portfolio Items", portfolios_path %> / 
      <a href="#">Back to top</a>
    </p>
    <p>
      <%= copyright_generator %>
    </p>
  </div>
</footer>

app/views/shared/_portfolio_masthead.html.erb
<section class="py-5 text-center container">
  <div class="row py-lg-5">
    <div class="col-lg-6 col-md-8 mx-auto">
      <h1 class="fw-light">My Portfolio</h1>
      <p class="lead text-body-secondary">Showcasing a curated selection of my Ruby on Rails applications, this portfolio highlights projects that demonstrate my expertise in building dynamic, responsive, and user-centric web solutions..</p>
      <p>
        <%= link_to 'Find Out More About Me', about_me_path, class: 'btn btn-primary' %>
        <%= link_to 'My Blog', blogs_path, class: 'btn btn-secondary' %>
      </p>
    </div>
  </div>
</section>

app/views/shared/_portfolio_nav.html.erb
<header data-bs-theme="dark">
  <div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
      <div class="row">
        <div class="col-sm-8 col-md-7 py-4">
          <h4>About</h4>
          <p class="text-body-secondary">Add some information about the album below, the author, or any other background context. Make it a few sentences long so folks can pick up some informative tidbits. Then, link them off to some social networking sites or contact information.</p>
        </div>
        <div class="col-sm-4 offset-md-1 py-4">
          <h4>Explore</h4>
          <ul class="list-unstyled">
            <%= nav_helper 'text-white', 'li' %>
            <li><%= login_helper 'text-white' %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>
  <div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
      <a href="/" class="navbar-brand d-flex align-items-center">
        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" aria-hidden="true" class="me-2" viewBox="0 0 24 24"><path d="M23 19a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h4l2-3h6l2 3h4a2 2 0 0 1 2 2z"/><circle cx="12" cy="13" r="4"/></svg>
        <strong>April Campos</strong>
      </a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
    </div>
  </div>
</header>